### ISSUE TITLE
Adding ZPAQ compression?

### ISSUE THREAD

**Issue by IngwiePhoenix** [coder543/libcanister#1]
libcanister is - even today! - the only C++ library with an actual file archiving. miniz/minizip also exist, but libcanister is the only real C++ library, which is why I still consider it a dependency in my project. Now, I want to power it up and add this: http://mattmahoney.net/dc/zpaq.html

Where/how would I go about to add this?

Kind regards, Ingwie

**Comment by coder543** [comment]
zpaq appears to be a complete solution for backing up already. What exactly do you want to do with zpaq and libcanister?

**Comment by IngwiePhoenix** [comment]
Within the ZPAQ C++ API, you have a Reader and Writer class. These are used to read and write compressed data. The backup solution is inside the tool that they provide in the download - it can indeed archive files. Within that tool’s source, I can see that they have implemented some kind of archiving functionality, but i didn’t understand how.

What I want to do with libcanister and that is, that libcanister archives are written and read through the ZPAQ compression algorithm to obtain a high level of compression. For my project, I am going to bundle a lot of assets together, but I also want to use encryption. ZPAQ supports AES encryption. That would mean that I can use the easy API of libcanister but get maximum compression and encryption through ZPAQ.

**Comment by coder543** [comment]
I really don't have much time right now to work on this, and I don't know anything about ZPAQ beyond what you've told me. If you want to implement encryption in libcanister, my recommendation is to look at the [libcanfile.cpp](https://github.com/coder543/libcanister/blob/master/src/libcanfile.cpp) code. Whenever it loads up a file from disk and caches it, you could add a line of code to intercept and then decrypt the file contents, and whenever it dumps the cache back to disk you could encrypt the file contents. You could use an AES library [like this one](http://brgladman.org/oldsite/AES/index.php), or some other one. I don't think there's any need to use ZPAQ.

If you do get anything done with encryption, feel free to send me a pull request and I'll take a look at it.
